-- Data for FARMERS 

INSERT INTO FARMERS (FARMER_ID, FIRST_NAME, LAST_NAME, CONTACT_EMAIL)
VALUES (FARMERS_SEQ.NEXTVAL, 'Benson', 'Gatete', 'benson.g@agrotech.com');
INSERT INTO FARMERS (FARMER_ID, FIRST_NAME, LAST_NAME, CONTACT_EMAIL)
VALUES (FARMERS_SEQ.NEXTVAL, 'Chantal', 'Mutesi', 'chantal.m@agrotech.com');
INSERT INTO FARMERS (FARMER_ID, FIRST_NAME, LAST_NAME, CONTACT_EMAIL)
VALUES (FARMERS_SEQ.NEXTVAL, 'David', 'Habimana', 'david.h@agrotech.com');

-- Data for CROP_TYPES 

INSERT INTO CROP_TYPES (TYPE_ID, NAME, GROWTH_DURATION_DAYS, WATER_REQUIREMENT)
VALUES (CROP_TYPES_SEQ.NEXTVAL, 'Maize', 120, 'Medium'); -- ID 1
INSERT INTO CROP_TYPES (TYPE_ID, NAME, GROWTH_DURATION_DAYS, WATER_REQUIREMENT)
VALUES (CROP_TYPES_SEQ.NEXTVAL, 'Potatoes', 90, 'High'); -- ID 2
INSERT INTO CROP_TYPES (TYPE_ID, NAME, GROWTH_DURATION_DAYS, WATER_REQUIREMENT)
VALUES (CROP_TYPES_SEQ.NEXTVAL, 'Beans', 75, 'Low');    -- ID 3
INSERT INTO CROP_TYPES (TYPE_ID, NAME, GROWTH_DURATION_DAYS, WATER_REQUIREMENT)
VALUES (CROP_TYPES_SEQ.NEXTVAL, 'Coffee', 365, 'Medium'); -- ID 4

-- Data for FARMS 
-- Benson's Farms (FARMER_ID 1)

INSERT INTO FARMS (FARM_ID, FARMER_ID, NAME, LOCATION_COORD)
VALUES (FARMS_SEQ.NEXTVAL, 1, 'East Valley Farm', '1.940 S, 30.050 E'); -- ID 1
INSERT INTO FARMS (FARM_ID, FARMER_ID, NAME, LOCATION_COORD)
VALUES (FARMS_SEQ.NEXTVAL, 1, 'Riverside Plot', '1.800 S, 30.200 E');  -- ID 2
-- Chantal's Farm (FARMER_ID 2)
INSERT INTO FARMS (FARM_ID, FARMER_ID, NAME, LOCATION_COORD)
VALUES (FARMS_SEQ.NEXTVAL, 2, 'Highland Estate', '2.500 S, 29.500 E'); -- ID 3

-- Data for Inventory

INSERT INTO INVENTORY (INVENTORY_ID, FARM_ID, ITEM_NAME, UNIT, STOCK_QUANTITY)
VALUES (INVENTORY_SEQ.NEXTVAL, 1, 'Maize Seeds (Type A)', 'KG', 500.00);  -- ID 1
INSERT INTO INVENTORY (INVENTORY_ID, FARM_ID, ITEM_NAME, UNIT, STOCK_QUANTITY)
VALUES (INVENTORY_SEQ.NEXTVAL, 1, 'Fertilizer NPK 10-10-10', 'KG', 1500.00); -- ID 2
INSERT INTO INVENTORY (INVENTORY_ID, FARM_ID, ITEM_NAME, UNIT, STOCK_QUANTITY)
VALUES (INVENTORY_SEQ.NEXTVAL, 2, 'Potato Seeds (Kerr)', 'KG', 800.00); -- ID 3
INSERT INTO INVENTORY (INVENTORY_ID, FARM_ID, ITEM_NAME, UNIT, STOCK_QUANTITY)
VALUES (INVENTORY_SEQ.NEXTVAL, 2, 'Pesticide (Fungicide)', 'LITER', 25.50); -- ID 4

-- Data for Crops

INSERT INTO CROPS (CROP_ID, FARM_ID, TYPE_ID, PLANTING_DATE)
VALUES (CROPS_SEQ.NEXTVAL, 1, 1, DATE '2025-09-01'); -- ID 1
INSERT INTO CROPS (CROP_ID, FARM_ID, TYPE_ID, PLANTING_DATE)
VALUES (CROPS_SEQ.NEXTVAL, 2, 2, DATE '2025-10-15'); -- ID 2
INSERT INTO CROPS (CROP_ID, FARM_ID, TYPE_ID, PLANTING_DATE)
VALUES (CROPS_SEQ.NEXTVAL, 3, 3, DATE '2025-11-20'); -- ID 3
INSERT INTO CROPS (CROP_ID, FARM_ID, TYPE_ID, PLANTING_DATE)
VALUES (CROPS_SEQ.NEXTVAL, 1, 4, DATE '2025-01-01'); -- ID 4
