-- ***************************************************************
-- FILE 01: DDL (DATA DEFINITION LANGUAGE) - TABLE AND SEQUENCE CREATION
-- PHASE III, V, & VII SCHEMA IMPLEMENTATION
-- ***************************************************************

-- 1. CORE MASTER TABLES
CREATE TABLE FARMERS (
    FARMER_ID       NUMBER(10)      PRIMARY KEY,
    FIRST_NAME      VARCHAR2(50)    NOT NULL,
    LAST_NAME       VARCHAR2(50)    NOT NULL,
    CONTACT_EMAIL   VARCHAR2(100)   UNIQUE
);

CREATE TABLE CROP_TYPES (
    TYPE_ID                 NUMBER(10)      PRIMARY KEY,
    NAME                    VARCHAR2(50)    UNIQUE NOT NULL,
    GROWTH_DURATION_DAYS    NUMBER(5)       NOT NULL
);

-- 2. LOCATION AND TRANSACTIONAL TABLES
CREATE TABLE FARMS (
    FARM_ID         NUMBER(10)      PRIMARY KEY,
    FARMER_ID       NUMBER(10)      NOT NULL,
    NAME            VARCHAR2(100)   NOT NULL,
    -- FOREIGN KEY
    CONSTRAINT fk_farm_farmer FOREIGN KEY (FARMER_ID)
        REFERENCES FARMERS(FARMER_ID)
);

CREATE TABLE CROPS (
    CROP_ID                 NUMBER(10)      PRIMARY KEY,
    FARM_ID                 NUMBER(10)      NOT NULL,
    TYPE_ID                 NUMBER(10)      NOT NULL,
    PLANTING_DATE           DATE            NOT NULL,
    -- FOREIGN KEYS
    CONSTRAINT fk_crop_farm FOREIGN KEY (FARM_ID)
        REFERENCES FARMS(FARM_ID),
    CONSTRAINT fk_crop_type FOREIGN KEY (TYPE_ID)
        REFERENCES CROP_TYPES(TYPE_ID)
);

CREATE TABLE INVENTORY (
    INVENTORY_ID    NUMBER(10)      PRIMARY KEY,
    FARM_ID         NUMBER(10)      NOT NULL,
    ITEM_NAME       VARCHAR2(50)    NOT NULL,
    STOCK_QUANTITY  NUMBER(10,2)    NOT NULL,
    -- CONSTRAINT: Ensures inventory never goes negative
    CONSTRAINT fk_inventory_farm FOREIGN KEY (FARM_ID)
        REFERENCES FARMS(FARM_ID),
    CONSTRAINT check_stock_qty CHECK (STOCK_QUANTITY >= 0)
);

CREATE TABLE WEATHER (
    WEATHER_ID          NUMBER(10)      PRIMARY KEY,
    FARM_ID             NUMBER(10)      NOT NULL,
    OBSERVATION_DATE    DATE            NOT NULL,
    RAINFALL_MM         NUMBER(5,2),
    -- CONSTRAINT: Ensures only one weather record per farm per day
    CONSTRAINT fk_weather_farm FOREIGN KEY (FARM_ID)
        REFERENCES FARMS(FARM_ID),
    CONSTRAINT unq_weather_obs UNIQUE (FARM_ID, OBSERVATION_DATE)
);

CREATE TABLE SCHEDULES (
    SCHEDULE_ID             NUMBER(10)      PRIMARY KEY,
    CROP_ID                 NUMBER(10)      NOT NULL,
    TASK_TYPE               VARCHAR2(50)    NOT NULL,
    DUE_DATE                DATE            NOT NULL,
    COMPLETION_DATE         DATE,
    RESOURCE_USED_ID        NUMBER(10),
    RESOURCE_QUANTITY_NEEDED NUMBER(10,2),
    -- FOREIGN KEYS
    CONSTRAINT fk_schedule_crop FOREIGN KEY (CROP_ID)
        REFERENCES CROPS(CROP_ID),
    CONSTRAINT fk_schedule_inventory FOREIGN KEY (RESOURCE_USED_ID)
        REFERENCES INVENTORY(INVENTORY_ID)
);

CREATE TABLE ALERTS (
    ALERT_ID        NUMBER(10)      PRIMARY KEY,
    FARM_ID         NUMBER(10)      NOT NULL,
    ALERT_DATE      DATE            DEFAULT SYSDATE NOT NULL,
    ALERT_TYPE      VARCHAR2(50)    NOT NULL,
    MESSAGE         VARCHAR2(255)   NOT NULL
);

-- 3. PHASE VII: SECURITY AND AUDITING TABLES
CREATE TABLE HOLIDAYS (
    HOLIDAY_DATE    DATE            PRIMARY KEY,
    HOLIDAY_NAME    VARCHAR2(100)   NOT NULL
);

CREATE TABLE AUDIT_LOG (
    AUDIT_ID        NUMBER(10)      PRIMARY KEY,
    TRANSACTION_DATE DATE           DEFAULT SYSDATE NOT NULL,
    USER_NAME       VARCHAR2(50)    NOT NULL,
    TABLE_NAME      VARCHAR2(50)    NOT NULL,
    ACTION_TYPE     VARCHAR2(10)    NOT NULL,
    STATUS          VARCHAR2(10)    NOT NULL,
    REASON          VARCHAR2(255)
);

-- 4. SEQUENCE CREATION
CREATE SEQUENCE FARMERS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CROP_TYPES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE FARMS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE CROPS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE WEATHER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE INVENTORY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SCHEDULES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE ALERTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE AUDIT_LOG_SEQ START WITH 1 INCREMENT BY 1;

--5. Additional Holiday Table Creation

CREATE TABLE HOLIDAYS (
    HOLIDAY_DATE DATE PRIMARY KEY,
    HOLIDAY_NAME VARCHAR2(100) NOT NULL,
    FARM_ID  NUMBER(10) 
);

--6. Audit Log Table will be capturing every attempt at DML on the monitored tables, fulfilling the auditing requirement

CREATE TABLE AUDIT_LOG (
    AUDIT_ID NUMBER(10) PRIMARY KEY,
    TRANSACTION_DATE DATE DEFAULT SYSDATE NOT NULL,
    USER_NAME VARCHAR2(50) DEFAULT USER NOT NULL,
    TABLE_NAME VARCHAR2(50) NOT NULL,
    ACTION_TYPE VARCHAR2(10) NOT NULL, -- 'INSERT', 'UPDATE', 'DELETE'
    STATUS VARCHAR2(10) NOT NULL, -- 'ALLOWED', 'DENIED'
    REASON VARCHAR2(255)
);
